[workspace]
resolver = "3"

[workspace.package]
version = "0.0.8"
edition = "2024"
keywords = ["ASIO", "audio", "media", "sound", "steinberg"]
categories = ["hardware-support", "multimedia", "multimedia::audio"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/LastExceed/azo"

[package]
name = "azo"
description = "Re-implementation of ASIO (Audio Stream Input/Output)"
publish = true
version.workspace = true
edition.workspace = true
keywords.workspace = true
categories.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true

[features]
default = ["undocumented"]
undocumented = []

[dependencies]
azo-sys = { path = "./azo-sys", version = "0.0.8" }
windows-core = "0.62.2"
windows-registry = "0.6.1"

[build-dependencies]
windows-bindgen = "0.66.0"
